package com.kristian.flightsearch.datagenerator;

/*
 * FlightReader.java - Loads flight data from a text file
 *
 * This class reads flight information from a CSV-formatted text file and returns
 * a HashMap of flights indexed by flight number.
 *
 * File format (flights.txt):
 *   FlightNumber,Origin,Destination,Distance,DepartureTime,Price
 *   AA 1234,JFK,LAX,2475.0,08:30,350
 *   UA 5678,ORD,DEN,920.0,14:15,180
 *
 * The flight data is generated by FlightWriter and represents simulated flights
 * between airports in the network.
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.IOException;
import java.time.LocalTime;
import java.util.HashMap;

import com.kristian.flightsearch.models.Airport;
import com.kristian.flightsearch.models.Flight;

public class FlightReader {

    /**
     * Reads flights from a CSV file and returns them as a HashMap
     *
     * @param filePath Path to the flights file (e.g., "flights.txt")
     * @param airports Array of airports (needed to look up Airport objects by code)
     * @return HashMap where key = flight number, value = Flight object
     */
    public static HashMap<String, Flight> readFlights(String filePath, Airport[] airports) {
        HashMap<String, Flight> flightList = new HashMap<>();

        try {
            // Get a reader (tries classpath first for JAR, then filesystem for local dev)
            BufferedReader reader = getReader(filePath);
            if (reader == null) {
                System.err.println("Could not find flights file: " + filePath);
                return flightList;
            }

            String line;
            boolean isHeader = true;

            while ((line = reader.readLine()) != null) {
                // Skip the header line (first line with column names)
                if (isHeader) {
                    isHeader = false;
                    continue;
                }

                // Parse CSV: FlightNumber,Origin,Destination,Distance,DepartureTime,Price
                String[] parts = line.split(",");
                if (parts.length >= 6) {
                    String flightNumber = parts[0];
                    String originCode = parts[1];
                    String destCode = parts[2];
                    double distance = Double.parseDouble(parts[3]);
                    LocalTime departureTime = LocalTime.parse(parts[4]);
                    int price = Integer.parseInt(parts[5]);

                    // Look up the Airport objects by their codes
                    Airport origin = findAirportByCode(airports, originCode);
                    Airport destination = findAirportByCode(airports, destCode);

                    // Only create the flight if both airports exist in our data
                    if (origin != null && destination != null) {
                        Flight flight = new Flight(origin, destination, distance, departureTime, flightNumber);
                        flight.setPrice(price);  // Override the auto-generated price with the stored price
                        flightList.put(flightNumber, flight);
                    }
                }
            }
            reader.close();
        } catch (IOException e) {
            System.err.println("Error reading flights from file: " + e.getMessage());
        }

        return flightList;
    }

    /**
     * Gets a reader for the file - tries classpath first (for JAR), then filesystem (for local dev)
     *
     * This is the same pattern as FileReader.getReader() - we need it in both places
     * because this class uses static methods while FileReader uses instance methods.
     */
    private static BufferedReader getReader(String filePath) {
        // Try classpath first (works when running from JAR)
        InputStream is = FlightReader.class.getClassLoader().getResourceAsStream(filePath);
        if (is != null) {
            return new BufferedReader(new InputStreamReader(is));
        }

        // Fall back to filesystem (works for local development)
        File file = new File(filePath);
        if (file.exists()) {
            try {
                return new BufferedReader(new java.io.FileReader(file));
            } catch (Exception e) {
                return null;
            }
        }

        return null;
    }

    /**
     * Helper method to find an airport by its code in the airports array
     * This is O(n) - we could use a HashMap for O(1) but for 100 airports it's fine
     */
    private static Airport findAirportByCode(Airport[] airports, String code) {
        for (Airport airport : airports) {
            if (airport.getCode().equals(code)) {
                return airport;
            }
        }
        return null;
    }

}
